### PR TITLE
14 structure create a class picture

### LINKED ISSUE #14: [structure] Create a class Picture
A class Image is very usefull to store all the informations and pixels of the file. Then, we can easily modify the picture and export it.

### PR DESCRIPTION
**Pull request by aladin-heig**
~~I also added function to read and write files so both issues about this part are useless~~
Implement the BMPImage and BMPHeader classes to handle the BMP pictures. Read and write function are not yet functional, but will be implemented in #6 and #7

### CODE REVIEW

**Comment by Arthur2479** [comment]
I think it's a better practice to link the issues to this PR, so they'll be closed automatically. I reopened them.

**Review by Arthur2479 — CHANGES_REQUESTED** [review]
We can't use ImageIO to open the picture as stated [here](https://github.com/heig-vd-dai-course/heig-vd-dai-course/blob/main/07-practical-work-1/COURSE_MATERIAL.md#constraints). We must use classes seen in the course.

**Comment by Arthur2479** [comment]
@aladin-heig I reworked the Picture class, adding a Header class to manage headers. It seems I can't add you as a reviewer as you created the issue, so please review the code, write a comment with your remarks if any, then I will auto approve this.

FYI: The reading and writing are not (fully) implemented yet, so the 2 related issues do make sense and do not need to be linked to this PR

**Comment by aladin-heig** [comment]
@Arthur2479 As discussed in Teams, the small issue about spotless was resolved, you can merge this branch.

**Review by Arthur2479 — APPROVED** [review]

**Pull request merged**
